# Generated by Django 4.0.6 on 2022-07-27 09:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='hobbies',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.hobbies'),
        ),
    ]
