# Generated by Django 4.0.6 on 2022-07-27 11:20

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0002_blog_hobbies'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Hobbies',
            new_name='Hobby',
        ),
        migrations.RenameModel(
            old_name='Projects',
            new_name='Project',
        ),
        migrations.RenameField(
            model_name='blog',
            old_name='hobbies',
            new_name='hobby',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='hobbies',
            new_name='hobby',
        ),
    ]
